### ISSUE TITLE
don't work EMMET!!!

### ISSUE THREAD

**Issue by robotcigan** [davidrios/jade-tmbundle#58] opened 2015-10-24 21:51 UTC
# Now in jade don't work emmet
screenshot
http://joxi.ru/E2pdlMRfnzLy2Y

**Comment by petsto** [comment] 2015-10-24 22:44
Awesome job! Just a small issues with latest version...
Emet... and autocomplete for simple HTML tags like img, button, input and so on, don't work anymore.
Regards!

**Comment by davidrios** [comment] 2015-10-26 13:34
This highlighter doesn't have any autocomplete. Are you using some other package to provide autocompletion?

**Comment by davidrios** [comment] 2015-10-26 13:52
https://github.com/P233/Jade-Snippets-for-Sublime-Text-2/pull/14

**Comment by delch** [comment] 2015-10-26 14:16
Add in your emmet key binding this code:
```
[
    {
        "keys": [
            "tab"
        ],
        "command": "expand_abbreviation_by_tab",
        "context": [
            {
                "operand": "source.css, source.sass, source.less, source.scss, source.stylus, source.jade, text.jade, text.slim, text.xml, text.html - source, text.haml, text.scala.html, source string",
                "operator": "equal",
                "match_all": true,
                "key": "selector"
            },
            {
                "operand": "storage.type.templatetag.django",
                "operator": "not_equal",
                "match_all": true,
                "key": "selector"
            },
            {
                "match_all": true,
                "key": "selection_empty"
            },
            {
                "operator": "equal",
                "operand": false,
                "match_all": true,
                "key": "has_next_field"
            },
            {
                "operator": "equal",
                "operand": false,
                "match_all": true,
                "key": "setting.disable_tab_abbreviations"
            },
            {
                "operand": false,
                "operator": "equal",
                "match_all": true,
                "key": "auto_complete_visible"
            },
            {
                "match_all": true,
                "key": "is_abbreviation"
            }
        ]
    },
    {
        "keys": [
            "tab"
        ],
        "command": "expand_abbreviation_by_tab",
        "context": [
            {
                "operand": "source.css, source.sass, source.less, source.scss, source.stylus, source.jade, text.jade, text.slim, text.xml, text.html - source, text.haml, text.scala.html, source string",
                "operator": "equal",
                "match_all": true,
                "key": "selector"
            },
            {
                "operand": "storage.type.templatetag.django",
                "operator": "not_equal",
                "match_all": true,
                "key": "selector"
            },
            {
                "match_all": true,
                "key": "selection_empty"
            },
            {
                "operator": "equal",
                "operand": false,
                "match_all": true,
                "key": "has_next_field"
            },
            {
                "operator": "equal",
                "operand": true,
                "match_all": true,
                "key": "auto_complete_visible"
            },
            {
                "operator": "equal",
                "operand": false,
                "match_all": true,
                "key": "setting.disable_tab_abbreviations_on_auto_complete"
            },
            {
                "match_all": true,
                "key": "is_abbreviation"
            }
        ]
    }
]
```

**Comment by davidrios** [comment] 2015-10-26 14:26
@delch in the last version I changed the scope from `source.jade` to `text.jade`, maybe you should change is the appropriate location on emmet.

**Comment by delch** [comment] 2015-10-26 14:29
@davidrios i think @sergeche must do it, right, Sergey ?

**Comment by davidrios** [comment] 2015-10-26 14:30
@delch Yeah, I deleted my comment when I realized you were not the maintainer.

**Comment by davidrios** [comment] 2015-10-26 14:32
@sergeche I changed the scope for the Jade highlighter from `source.jade` to `text.jade` and it seems to be causing some issues with other packages. Could you take a look on that at Emmet?

**Comment by xiansheng** [comment] 2015-10-26 15:09
help pls for windows guys, same issue

**Comment by davidrios** [comment] 2015-12-01 13:59
I'm closing this for lack of further feedback and because the problem is not with this package.

**Closed by davidrios** 2015-12-01 13:59 UTC

**Comment by sergeche** [comment] 2015-12-01 14:00
Problem is already solved in Emmet

**Comment by davidrios** [comment] 2015-12-01 14:06
@sergeche Thank you.
