### ISSUE TITLE
Can cause Sublime Text 3 to stop responding

### ISSUE THREAD

**Issue by JamieMason** [davidrios/jade-tmbundle#86] opened 2016-09-22 15:37 UTC
Hi, thanks for making this package. 

I just noticed that opening [**FreeCodeCamp/FreeCodeCamp**/server/views/partials/scripts.jade](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/e72ad8c513dc07e8c8df787d988ebf75d4130661/server/views/partials/scripts.jade) causes Sublime Text 3 to stop responding and require force-quitting. I have tried this a couple of times before finally uninstalling the Jade package, which results in the file being possible to open.

``` jade
script.
    (function(i,s,o,g,r,a,m){ i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-55446531-1', 'auto');
    ga('require', 'displayfeatures');
    ga('send', 'pageview');
// Leave the below lines alone!
script.
  (function(global) {
    global.main = global.main || {};
    global.main.isLoggedIn = !{JSON.stringify(!!user)};
    global.main.userId = !{JSON.stringify(user && user.id || false)};
  }(window))
script(src=rev('/js', 'vendor-main.js'))
script(src=rev('/js', 'main.js'))
```

I am using Stable Channel Build 3124 on OS X El Capitan 10.11.6 (15G1004).

I hope something here will be useful to help improve the package, thanks for your time.

Jamie

**Comment by davidrios** [comment] 2016-09-22 19:28
Probably duplicate of #85, please try the solutions there.

**Closed as completed by davidrios** 2016-09-22 19:28 UTC

**Comment by JamieMason** [comment] 2016-09-22 21:26
Thanks David 👍

**Comment by davidrios** [comment] 2016-09-22 21:35
=)

**Comment by davidrios** [comment] 2016-09-25 16:16
Did you try the latest stable build 3126? I tested here and it seems to have resolved the issue.

**Comment by JamieMason** [comment] 2016-09-25 16:19
Great thanks, I'll give that a try.
