### ISSUE TITLE
Does not autobuild .jade files anymore

### ISSUE THREAD

**Issue by J-Kallunki** [davidrios/jade-tmbundle#57] opened 2015-10-24 09:07 UTC
works with checkout fea35b5

**Comment by davidrios** [comment] 2015-10-24 13:36
What is your configuration to enable autobuild?

**Comment by J-Kallunki** [comment] 2015-10-24 14:27
Should be defaults. And works with checkout fea35b5.
SublimeOnSaveBuild.sublime-settings:
```
{
    "filename_filter": "\\.(css|js|sass|less|scss|jade)$",
    "build_on_save": 1
}
```
Jade.sublime-build:
```
{
	"cmd": ["jade", "$file", "--pretty"],
	"selector": "source.jade",
	"osx": {"path": "/usr/local/bin:$PATH"},
	"windows": {"shell": "true"}
}
```

**Comment by davidrios** [comment] 2015-10-24 16:58
I guess it will work if you change `"selector": "source.jade"` to `"selector": "text.jade"`.

**Comment by davidrios** [comment] 2015-10-26 13:32
Could you please try this version of sublime build: https://github.com/davidrios/Sublime-Jade-Build
and tell me if that solves this problem?

**Comment by davidrios** [comment] 2015-12-01 13:59
I'm closing this for lack of further feedback and because the problem is not with this package.

**Closed by davidrios** 2015-12-01 13:59 UTC
